#!/bin/sh
battery_level="$(cat /sys/class/power_supply/BAT1/capacity)"
battery_stat="$(cat /sys/class/power_supply/BAT1/status)"

if [[ "$battery_stat" == "Charging" ]]; then
	[[ $battery_level -ge 90 ]] && notify-send "Battery charged."

	logo=""
else
	if [[ $battery_level -le 15 ]]; then
		logo=" "
               	notify-send --urgency=critical "Battery low, plug the charger in"
        
	elif [[ $battery_level -ge 90 ]]; then
		logo=" "
        
	else
		logo=""
	fi

fi

echo "$logo $battery_level"
